### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [4]:
x = np.array([1, 2, 3, 4])
print(x) # 1차원 vector

y = np.array([[2, 3, 4], [1, 2, 5]]) # 거의 쓰지 않는 방법
print(y) # 2차원 vector

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [11]:
np.arange(10) # 0부터 시작해서 10전까지

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1, 10) # 1부터 시작해서 10전까지

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 10, 2) # 1부터 시작해서 10전까지 2씩 띄어서

array([1, 3, 5, 7, 9])

In [14]:
np.arange(5, 101, 5) # 5부터 시작해서 101전까지 5씩 띄어서

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [18]:
np.ones((4, 5)) # (4, 5) : tuple 형태 -> 4행 5열의 1로 구성된 행렬

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((2,3,4)) # 3행 4열의 1로 구성된 행렬 2개 : 3차원

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((2,2,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [23]:
np.empty((3, 4)) # 어떤 값이 아니라 '초기화된 값'으로 행렬을 구성하고 싶을 때

array([[1.28822975e-231, 2.00389709e+000, 2.96439388e-323,
        0.00000000e+000],
       [0.00000000e+000, 3.76231868e+174, 6.87153230e-091,
        7.92560554e+165],
       [8.41453823e+164, 6.88907548e-042, 3.99910963e+252,
        8.34404819e-309]])

In [25]:
np.full((3, 4), 7) # ones나 zeros처럼 '특정한 수'로 행렬을 만들고 싶을 때

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [26]:
# 단위 행렬 : 대각선이 1이고 나머지가 0인 행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### np.linspace로 생성하기

In [29]:
np.linspace(1, 10, 3) # 1, 10은 시작과 끝, 3은 나누고자 하는 수 : 사이사이가 동일하게

array([ 1. ,  5.5, 10. ])

In [32]:
np.linspace(1, 10, 4) # 처음이 1이고 마지막이 10으로 4등분 해라 : x축 좌표에 많이 사용

array([ 1.,  4.,  7., 10.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [35]:
x= np.arange(1, 16)
print(x)

x.shape # tuple로 반환

x.reshape(3, 5) # 3행 5열로 바꿔라

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
x.reshape(5, 3, 1) # 3행 1열인 5개의 배열로 바꿔라 -> 3차원

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [38]:
x.reshape(5, 4) # error -> reshape에서 곱하는 숫자가 원래 배열의 숫자와 같은지 확인

ValueError: cannot reshape array of size 15 into shape (5,4)