### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [4]:
np.random.rand(2, 3) # 랜덤한 2행 3열 : 0과 1사이의 분포

array([[0.42035356, 0.27556562, 0.68239848],
       [0.72464913, 0.20142811, 0.72918208]])

In [6]:
np.random.rand(10) # 1차원 벡터

array([0.56382224, 0.46953226, 0.69090361, 0.19525917, 0.27488634,
       0.54056903, 0.24398104, 0.06469082, 0.26647276, 0.86241653])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [9]:
# 정규분포 안에서 랜덤한 sampling 하고 싶을 때
np.random.randn(3, 4) # 정규분포이기 때문에 음수값 가질 수 있음

array([[-2.35957301,  2.40891072, -0.28180577,  0.2496407 ],
       [-0.75267446, -1.71723854, -1.02680792, -0.50858948],
       [-1.81812262,  0.69308537, -0.34356819,  0.08933878]])

In [10]:
np.random.randn(3, 4, 2)

array([[[-1.53779132,  2.29105719],
        [-0.38413818, -0.84605633],
        [ 0.89796287,  0.0240947 ],
        [-0.04678395,  0.06284255]],

       [[-0.04072266,  0.05223824],
        [ 0.42784706,  0.53587012],
        [-0.26917639, -1.6540874 ],
        [ 0.40209685, -0.25272041]],

       [[ 0.10624436,  0.59785219],
        [ 0.08651716,  0.58133778],
        [ 2.17214198, -0.20137187],
        [ 0.74543781,  0.26710045]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [12]:
# 정수
np.random.randint(1, 100, size=(3, 5)) # 1~99사이에 3행 5열 정수 벡터

array([[27, 12, 69, 70, 61],
       [79, 55, 78, 68, 72],
       [15, 46, 57, 96, 69]])

In [13]:
np.random.randint(1, 100, size=5)

array([88, 78,  7, 16, 29])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [26]:
np.random.seed(100) # 아무 숫자나 넣어도 됨
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [28]:
np.random.choice(100, (3, 4)) # 1~99까지 숫자에서 3, 4 벡터를 가져와라

array([[71, 80,  2, 94],
       [19, 98, 63, 53],
       [27, 56, 30, 48]])

In [33]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2)) # 주어진 x에서 2,2 벡터를 가져와라, 중복 가능
np.random.choice(x, size=(2, 2), replace=False) # 중복 불가

array([[2.6, 2. ],
       [1. , 4.9]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [34]:
# uniform
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.33138675, 1.02277922, 1.21583553, 2.8020262 , 2.58975752],
       [2.62292196, 2.28055611, 2.24955902, 1.29101502, 2.1404318 ],
       [1.130225  , 1.62682514, 1.43413153, 2.05390078, 1.85421676],
       [2.96526085, 1.28090297, 2.49682321, 2.57768079, 2.46079323]])

In [36]:
# normal
np.random.normal(size=(3, 4)) # np.random.randn(3, 4) 와 동일한 것

array([[-0.12888604, -0.28292163, -0.17916825,  0.67575177],
       [ 2.38059534, -1.14670086, -0.29114335, -0.85422577],
       [ 0.86340647, -0.31638123, -0.90222577, -0.73856239]])