## 학습목표
 1. ndarray shape 변경하기

In [2]:
# 데이터의 형태를 바꾼다는 것 : 데이터의 차원을 바꾸고, 값도 바꿀 수 있다는 것
import numpy as np

#### ravel, np.ravel
  - 다차원배열을 1차원으로 변경
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F - column 우선 변경

In [6]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [7]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.ravel(x) # x.ravel() 과 똑같은 것

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
temp = x.ravel()
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
temp[0] = 100
print(temp)
print(x) # ravel은 복사본을 만드는 것이 아니라 데이터를 그대로 가져옴, 값이 바뀌면 다 바뀌는 것₩

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [24]:
np.ravel(x, order='C') # 기본값 C : 열을 기준으로 펴짐

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [25]:
np.ravel(x, order='F') # 행을 기준으로 펴짐

array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

#### flatten
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [21]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
y.flatten() # np.flatten(y) 가 안됨!!!!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
temp2 = y.flatten()
print(temp2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
temp2[0]=100
print(temp2)
print(y) # flatten 은 내부적으로 복사본을 만드는 것, 원래의 값은 그대로 있음

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
y.flatten(order='F') # 열을 기준으로 펴짐

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [28]:
x = np.arange(30).reshape(2, 3, 5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [29]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#### reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

In [32]:
x = np.arange(36)
print(x)
print(x.shape) # 일차원이기 때문에
print(x.ndim) # 차원

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
(36,)
1


In [35]:
x.reshape(6, -1) # 하나의 값을 확정지으면 나머지 숫자는 확정될 수 있음 : "-1" 쓰면 자동으로 유추

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
x.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
x.reshape(6, 5) # 곱이 안맞는 경우 -> error!

ValueError: cannot reshape array of size 36 into shape (6,5)

In [39]:
y = x.reshape(6, -1)
print(y.shape) # 차원
print(y.ndim) # shape의 길이

(6, 6)
2


In [42]:
k = x.reshape(3,-1,4) # 두개가 확정 시에 나머지 하나는 유추 가능 : -1 사용
print(k)
print(k.shape)
print(k.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
(3, 3, 4)
3
