## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [2]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.54818723 0.96248612 0.13746281 0.54864939 0.80111356]
 [0.36762615 0.25204394 0.86927278 0.25017818 0.10785436]
 [0.60591239 0.25539485 0.43144596 0.44637084 0.65403481]]


#### 연산 함수
 - add, substract, multiply, divide -> 모든 연산은 shape이 같아야 함!!

In [4]:
np.add(x, y) # 똑같은 인덱스의 것들끼리 더해서 새로운 값 도출 : 다른 shape을 가지는 것끼리 덧셈 X

array([[ 0.54818723,  1.96248612,  2.13746281,  3.54864939,  4.80111356],
       [ 5.36762615,  6.25204394,  7.86927278,  8.25017818,  9.10785436],
       [10.60591239, 11.25539485, 12.43144596, 13.44637084, 14.65403481]])

In [6]:
x + y

array([[ 0.54818723,  1.96248612,  2.13746281,  3.54864939,  4.80111356],
       [ 5.36762615,  6.25204394,  7.86927278,  8.25017818,  9.10785436],
       [10.60591239, 11.25539485, 12.43144596, 13.44637084, 14.65403481]])

In [7]:
x - y

array([[-0.54818723,  0.03751388,  1.86253719,  2.45135061,  3.19888644],
       [ 4.63237385,  5.74795606,  6.13072722,  7.74982182,  8.89214564],
       [ 9.39408761, 10.74460515, 11.56855404, 12.55362916, 13.34596519]])

In [8]:
x * y

array([[0.        , 0.96248612, 0.27492562, 1.64594818, 3.20445423],
       [1.83813075, 1.51226362, 6.08490946, 2.00142546, 0.97068928],
       [6.05912389, 2.80934336, 5.17735153, 5.80282098, 9.15648729]])

In [9]:
x / y

array([[ 0.        ,  1.03897602, 14.5493899 ,  5.46797286,  4.99304995],
       [13.60077348, 23.80537325,  8.05270815, 31.97720887, 83.44585835],
       [16.5040362 , 43.0705629 , 27.81344849, 29.12376591, 21.40558861]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [10]:
print(y)

[[0.54818723 0.96248612 0.13746281 0.54864939 0.80111356]
 [0.36762615 0.25204394 0.86927278 0.25017818 0.10785436]
 [0.60591239 0.25539485 0.43144596 0.44637084 0.65403481]]


In [11]:
# 평균 - 두가지 형태로 가능
np.mean(y) # (1)

0.48253555877944787

In [13]:
y.mean() # (2)

0.48253555877944787

In [14]:
# 최댓값
np.max(y)

0.9624861235501635

In [16]:
# 최댓값의 인덱스
np.argmax(y) # flatten한 형태로 가지고 옴

1

In [21]:
# 분산, 중앙값, 표준편차
np.var(y), np.median(y), np.std(y)

(0.06466785492657814, 0.44637084499196156, 0.2542987513272099)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [22]:
y

array([[0.54818723, 0.96248612, 0.13746281, 0.54864939, 0.80111356],
       [0.36762615, 0.25204394, 0.86927278, 0.25017818, 0.10785436],
       [0.60591239, 0.25539485, 0.43144596, 0.44637084, 0.65403481]])

In [23]:
np.sum(y)

7.238033381691718

In [25]:
np.cumsum(y) # 누적합계 : 리스트 - 뒤의 원소는 그 전까지와 자기의 합

array([0.54818723, 1.51067336, 1.64813616, 2.19678556, 2.99789912,
       3.36552527, 3.6175692 , 4.48684198, 4.73702017, 4.84487453,
       5.45078692, 5.70618177, 6.13762773, 6.58399858, 7.23803338])

In [27]:
sum(y) # 같은 열끼리 더한 것

array([1.52172577, 1.46992491, 1.43818155, 1.24519842, 1.56300273])

In [30]:
np.sum(y, axis=0) # 축을 따라 합함, default = None ( 전체의 값 더함 )

array([1.52172577, 1.46992491, 1.43818155, 1.24519842, 1.56300273])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [31]:
z = np.random.randn(10)
print(z)

[ 1.25153424 -2.70980589  1.19877584 -2.26692354  0.23590841 -0.97320829
  0.27069293 -0.10119298 -1.01293111  0.04060063]


In [33]:
z > 0

array([ True, False,  True, False,  True, False,  True, False, False,
        True])

In [34]:
np.any(z>0) # z > 0 의 값이 하나라도 참이면 true

True

In [35]:
np.all(z>0) # z > 0 의 값이 하나라도 거짓이면 false

False

In [37]:
np.all(z!=0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [4]:
z= np.random.randn(10)
print(z)

[ 0.85442557 -0.87901625  0.14687876 -0.49199352 -1.77195606 -0.51222129
 -0.75555661  0.16113844  0.38445084 -0.24410297]


In [40]:
np.where(z > 0, z, 0) # z>0 : 조건, 참 : z , 거짓 : 0

array([1.16453815, 1.70027322, 0.72350968, 0.12516417, 0.12071748,
       0.        , 0.        , 0.        , 0.57965364, 0.3329774 ])

In [5]:
np.where(z>0, 0, z)

array([ 0.        , -0.87901625,  0.        , -0.49199352, -1.77195606,
       -0.51222129, -0.75555661,  0.        ,  0.        , -0.24410297])