## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.36115083 0.50820421 0.82703562 0.35813302 0.17784738]
 [0.06577484 0.67928974 0.80647681 0.56028529 0.11043704]
 [0.23187676 0.27902451 0.8798422  0.68943064 0.78480927]]


In [3]:
x + y

array([[ 0.36115083,  1.50820421,  2.82703562,  3.35813302,  4.17784738],
       [ 5.06577484,  6.67928974,  7.80647681,  8.56028529,  9.11043704],
       [10.23187676, 11.27902451, 12.8798422 , 13.68943064, 14.78480927]])

In [4]:
x * y

array([[ 0.        ,  0.50820421,  1.65407125,  1.07439905,  0.71138953],
       [ 0.32887419,  4.07573845,  5.6453377 ,  4.48228235,  0.99393334],
       [ 2.31876765,  3.06926957, 10.55810636,  8.96259828, 10.98732981]])

* Scalar(상수)와의 연산

In [6]:
x + 2 # 상수는 어떠한 형태라도 더할 수 있음

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [7]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [8]:
x ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [9]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [22]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(100, 104)

print(a)
print(b)
print(c)

print(a.shape)
print(b.shape) # 뒤가 비었을 때 ((3,)처럼) 연산 가능
print(c.shape) # broadcasting : 뒤 차원과 비교

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[100 101 102 103]
(4, 3)
(3,)
(4,)


In [11]:
a + b # broadcasting 적용

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [17]:
a + c # broadcasting 적용 x

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [23]:
d = b.reshape(1, 3)
print(d.shape) # (3,)이든 (1,3)이든 뒤부터 비교해서 같으면 연산 가능
print(d)

(1, 3)
[[100 101 102]]


In [24]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])